export default {
  NEWS_RECEIVED: 'NEWS_RECEIVED',
  NEWSITEM_RECEIVED: 'NEWSITEM_RECEIVED',
  NEWSITEM_LOADING: 'NEWSITEM_LOADING',
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGGEDIN: 'USER_LOGGEDIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USERS_RECEIVED: 'USERS_RECEIVED',
  USER_DETAILS_RECEIVED: 'USER_DETAILS_RECEIVED',
  USER_DETAILS_SAVED: 'USER_DETAILS_SAVED',
  USER_DETAILS_DELETED: 'USER_DETAILS_DELETED',
  USER_DETAILS_LOADING: 'USER_DETAILS_LOADING',
  PROVINCE_SAVED:'PROVINCE_SAVED'
}